### PR TITLE
python3 guard for using rosmsg codec (take 2)

### LINKED ISSUE #132: regression on kinetic due to #127
The changes in #127 (https://github.com/ros/genpy/blob/kinetic-devel/src/genpy/generator.py#L761) adds the line:
```
codecs.lookup_error("rosmsg").msg_type = self._type
```
to deserialization. On kinetic this line throws LookupException with the message: `unknown error handler name 'rosmsg'`

The issue can be reproduced by using any package that has regenerated its messages since #127. The package where I discovered it was with rosbridge_suite.

This is how to reproduce it:
```
# Boot up the minimal ros image in docker
docker run -it -p 11311:11311 ros:kinetic-ros-core

# Update apt and install ros-kinetic-rosbridge-suite
apt update
apt install ros-kinetic-rosbridge-suite

# Start roscore
roscore
```

On the host computer run `docker ps` to get the container id.

Log into the container and start rosapi (from rosbridge_suite):
```
docker exec -it <CONTAINER ID> bash

# Inside the container
source /opt/ros/kinetic/setup.bash
rosrun rosapi rosapi_node
```

Log into the container and call service:
```
docker exec -it <CONTAINER ID> bash

# Inside the container
source /opt/ros/kinetic/setup.bash
rosservice call /rosapi/get_param what ever
```

The service call will fail when trying to deserialize the message.

This can probably also be done on your local machine, but I choose docker to make sure we have the same environment.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Replaces #133 (since I didn't have permissions to push to the forked branch) and closes #132.

This patch makes the remaining code for the custom codec error handler conditional on the Python version.

@gwendolynbrook @mikepurvis FYI

### CODE REVIEW

**Comment by mikepurvis** [comment]
If we're here anyway, should we check `hasattr(genpy, 'RosMsgUnicodeErrors')` before registering the handler, to cover the case where `genpy` is older on the target system than the machine that built the messages?

**Comment by dirk-thomas** [comment]
> should we check `hasattr(genpy, 'RosMsgUnicodeErrors')` before registering the handler

I am not sure I understand the proposed change. The registration (https://github.com/ros/genpy/pull/134/files#diff-f4626899ff80377c1eaf9d092e00785eR88) happens directly after defining the `RosMsgUnicodeErrors` class so I don't see how this needs to be conditional.

> to cover the case where `genpy` is older on the target system than the machine that built the messages?

Wouldn't that require all using code (`.decode('utf-8', 'rosmsg')`) to only use the custom error handler conditionally?

**Comment by mikepurvis** [comment]
Oh shoot, sorry yes— yeah, that would be much more invasive of a change. Disregard.

**Comment by mikepurvis** [comment]
Sorry for all the drama this ended up causing. :(

**Comment by dirk-thomas** [comment]
@mikepurvis No worry, all changes have a risk (which could have been avoided if this repo would have a `noetic-devel` branch). So this isn't on you alone :wink:

**Comment by gwendolynbrook** [comment]
@dirk-thomas @mikepurvis thanks for taking care of this (and apologies for the lag on my end; busy week + emails got sorted to spam :facepalm: )

**Comment by dirk-thomas** [comment]
@gwendolynbrook can you please still answer my previous question since that will determine if the merged pull request needs to be released soon or isn't urgent and might not be released at all.

**Comment by dirk-thomas** [comment]
> @dirk-thomas this questin? https://github.com/ros/genpy/issues/132#issuecomment-683924034

Yes.

**Pull request merged**
