### PR TITLE
(docs) Add automodule

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
As now the documentation is just empty.

I don't know how the ros docs get updated, but please update that one.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Friendly ping @mabelzhang @sloretz ;)

**Comment by sloretz** [comment]
This documentation?

http://docs.ros.org/en/noetic/api/genpy/html/

I think it gets run nightly by the doc jobs. It looks like it's configured from the wrong branch, so that will need to be fixed.

https://github.com/ros/rosdistro/blob/adf8deb0b90f58182e05489d3833d8c76b220ea7/noetic/distribution.yaml#L2461

I don't see how this PR could break anything, and there's nothing in the documentation to break, so I'm in favor of merging it and seeing what happens.

**Review by sloretz — APPROVED** [review]

**Comment by sloretz** [comment]
Opened rosdistro PR fixing doc/source job branches https://github.com/ros/rosdistro/pull/30926

**Comment by sloretz** [comment]
Thanks for the PR! It may take a day or two to see the documentation reflect the change

**Pull request merged**
