### PR TITLE
first attempt at relying on setuptools

### PR DESCRIPTION
**Pull request by asmodehn**

### CODE REVIEW

**Comment by asmodehn** [comment]
Note : this fails because of the way catkin execute the `setup.py` script (with `exec` instead of `runpy`). I'll make an issue and a PR on catkin repo for it...

**Comment by asmodehn** [comment]
https://github.com/ros/catkin/issues/872

**Comment by asmodehn** [comment]
Shouldn't this also run on Kinetic and Lunar on the buildfarm ?

**Comment by dirk-thomas** [comment]
#115 switched from `distutils` to `setuptools`. Since I don't think we want to duplicate the parsing logic in multiple Python packages I will go ahead and close this ticket for now.

**Pull request closed without merging**
