### PR TITLE
fix integer division for duration

### PR DESCRIPTION
**Pull request by dirk-thomas**
@ros/ros_team @eric-wieser Please review.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Looks good to me. Note that the comment ` unlike __floordiv__, this uses true div for float arg.` is now not helpful, as `__div__` is now identical to `__truediv__`

**Comment by eric-wieser** [comment]
In fact, using that reasoning I'd argue that `__div__` should be removed entirely and replaced with `__div__ = __truediv__`

**Comment by dirk-thomas** [comment]
Good point. I have removed the obsolete comment.

I will keep the deduplication for later to keep this minimal.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
