### PR TITLE
Simpler and more canonical hash

### PR DESCRIPTION
**Pull request by eric-wieser**
Marginally faster too

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This will change the hash of e.g. stored `TVal` objects. Since this would break stored data which rely on the old hash semantic I don't think this should be changed without a good reason.

**Comment by eric-wieser** [comment]
I'd argue that the only hash _semantic_ is that `x == y` implies `hash(x) == hash(y)` - from the docs:

>  The only required property is that objects which compare equal have the same hash value; it is advised to somehow mix together (e.g. using exclusive or) the hash values for the components of the object that also play a part in c

But the current implementation fails to meet even that (under a contrived scenario):

```
dt1 = Duration(1.0)
dt1.secs = 2.0  # ok, these properties

dt2 = Duration(2.0)

assert dt1 == dt2   # ok
assert hash(dt1) == hash(dt2) # AssertionError
```

Can you elaborate on what you mean about stored data?

**Comment by dirk-thomas** [comment]
The example indicates that setting `secs` to a float shouldn't be allowed. Instead all assignments should be converted to integer values. Then the semantic of the current hash function would be perfectly valid.

I thought about cases where users e.g. pickle a dictionary with times as the key. But I guess this only affects the in-memory representation of the dict. Not the pickled data. @ros/ros_team Do you think it is safe to change the hash function here?

Since even the new proposed hash would fail for the above example should we modify the access to the slots and always convert them to int to ensure a normalized representation?

**Comment by eric-wieser** [comment]
> Since even the new proposed hash would fail for the above example

Not true, because in python `1 == 1.0`, so the hash is required to be equal

**Comment by dirk-thomas** [comment]
@eric-wieser good point, that makes quite a difference.

**Comment by dirk-thomas** [comment]
Since nobody else raised any concerns I moved forward and cherry-picked your patch to the *kinetic-devel* branch: b244f2f50813ce0385c8673a899bce9e140a35d8

Thank you again.

**Pull request closed without merging**
